LOAD DATA CHARACTERSET UTF8
INFILE 'import_data.txt'
INTO TABLE USER_TEMP
REPLACE
FIELDS TERMINATED BY ','
(
  ID,
  NAME CHAR "UPPER(:NAME)",
  SURNAME CHAR "UPPER(:SURNAME)",
  EMAIL CHAR "UPPER(:EMAIL)",
  ROLE CHAR "UPPER(:ROLE)",
  SALARY DECIMAL EXTERNAL "ROUND(:SALARY, 1)"
)